stages:
    - test

variables:
  LD_LIBRARY_PATH: /opt/sqlite-compat-django/lib/
  TOX: "/opt/venv/python3.6/tox/bin/tox"

py36-django22:
    stage: test
    script: $TOX -e 'py36-django22'

py36-django30:
    stage: test
    script: $TOX -e 'py36-django30'

py36-django31:
    stage: test
    script: $TOX -e 'py36-django31'

py36-django32:
    stage: test
    script: $TOX -e 'py36-django32'

